version: '3'

services:
  app:
    image: <your-app-image>
    volumes:
      - ./logs/app:/var/logs/app
  database:
    image: <your-database-image>
    volumes:
      - ./logs/database:/var/logs/database
  web:
    image: <your-web-image>
    volumes:
      - ./logs/web:/var/logs/web

volumes:
  logs:
    driver: local

networks:
  app_net:
    driver: bridge
